name: Run build script and deploy site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: HTML5 Validator
        uses: Cyb3r-Jak3/html5validator-action@master
        with:
          root: .
          css: true
          
      - name: upload-log
        uses: actions/upload-artifact@v3
        with:
          name: log
          path: log.log
